---
- name: install nvidia-driver 1/3
  become: false
  command: helm repo add nvdp https://nvidia.github.io/k8s-device-plugin

- name: install nvidia-driver 2/3
  become: false
  command: helm repo update

- name: install nvidia-driver 3/3
  become: false
  command: helm upgrade -i nvdp nvdp/nvidia-device-plugin --namespace nvidia-device-plugin --create-namespace --version 0.14.1
