---
- name: Kubeadm Init
  command: kubeadm init --control-plane-endpoint={{ floating_ip }} --pod-network-cidr={{ pod_network_cidr}} --service-cidr={{ service_cidr }}

- name: Create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    mode: 0755

- name: Setup kubeconfig for ubuntu user
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Remove the taints on the master
  become: false
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

- name: download calico.yaml
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Luthoz005/horovod-cluster/main/calico-custom.yaml
    validate_certs: false
    dest: /opt/calico-custom.yaml


- name: Repalce the ip in calico-custom
  ansible.builtin.replace:
    path: /opt/calico-custom.yaml
    regexp: '      cidr: 10.4.233.0/16'
    replace: '      cidr: {{ pod_network_cidr }}'

- name: apply calico-operator
  become: false
  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/tigera-operator.yaml

- name: apply calico-custom
  become: false
  command: kubectl apply -f /opt/calico-custom.yaml

- name: install helm
  become: false
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: install nvidia-driver 1/3
  become: false
  command: helm repo add nvdp https://nvidia.github.io/k8s-device-plugin

- name: install nvidia-driver 2/3
  become: false
  command: helm repo update

- name: install nvidia-driver 3/3
  become: false
  command: helm upgrade -i nvdp nvdp/nvidia-device-plugin --namespace nvidia-device-plugin --create-namespace --version 0.14.1

- name: Gen join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false 
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

- name: Fetch kube config file into local kubernetes folder
  become: false
  ansible.builtin.fetch:
    flat: yes
    src: /home/ubuntu/.kube/config
    dest: /root/.kube/config
