apiVersion: v1
kind: PersistentVolume
metadata:
  name: horovod-ssh-pv
spec:
  capacity:
    storage: {{.Values.SSH_storage}} 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: {{.Values.ssh_folder}}
    server: {{.Values.nfs_ip}}
  persistentVolumeReclaimPolicy: Retain 