apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horovod-ssh-pvc
  namespace: horovod
spec:
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.SSH_storage}}
    volumeName: "horovod-ssh-pv"
