apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: horovod-folder-pvc
  namespace: horovod
spec:
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.Horovod_storage}}
    volumeName: "horovod-folder-pv"

