apiVersion: v1
kind: Pod
metadata:
  name: horovod-master
  namespace: horovod
  labels:
    app: horovod-master
spec:
  nodeName: d53cj4-master
  containers:
  - args:
    securityContext:
      privileged: true
    env:
    - name: NFS_SERVER
      value: "true"
    - name: SSH_SERVER
      value: "true"
    - name: SSH_SERVER_PORT
      value: "12345"
    - name: JUPYTER_LAB
      value: "true"
    - name: JUPYTERLAB_PASSWORD
      value: {{ .Values.JUPYTER_Passwd | toString }}
    - name: JUPYTERLAB_PORT
      value: "8888"
    - name: GENERATE_SSH_KEY
      value: "true"
    name: horovod
    image: git.sztaki.hu:5050/science-cloud/reference-architectures/horovod/horovod-gpu:v0.3.0
    ports:
    - containerPort: 8888
    volumeMounts:
    - name: horovod-folder-storage
      mountPath: /horovod
    - name: horovod-ssh-storage
      mountPath: /root/.ssh
    resources:
      limits:
        nvidia.com/gpu: 1
  volumes:
    - name: horovod-folder-storage
      persistentVolumeClaim:
        claimName: horovod-folder-pvc
    - name: horovod-ssh-storage
      persistentVolumeClaim:
        claimName: horovod-ssh-pvc
