apiVersion: v1
kind: Service
metadata:
  namespace: horovod
  name: horovod-master
spec:
  type: NodePort
  selector:
    app: horovod-master
  ports:
    - protocol: TCP
      port: 8888
      nodePort: {{ .Values.NODEPort}}
