- name: Create Kubernetes master
  hosts: k8s_master
  remote_user: ubuntu
  become: yes
  vars_files:
  - "var_file.yml"
  roles:
    - containerd
    - role: nvidia_roles
      when: driverInstall == 'true'
    - kubernetes_setup
    - kubernetes_master
    - role: nvidia_helm
      when: driverInstall == 'true'