---
- name: setup nfs
  hosts: k8s_worker
  remote_user: ubuntu
  become: yes
  vars_files:
  - "var_file.yml"
  roles:
    - containerd
    - role: nvidia_roles
      when: driverInstall == 'true'
    - kubernetes_setup
    - kubernetes_worker
    - role: nvidia_helm
      when: driverInstall == 'true'
